version: '3'

# Postgres
services:
    database:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - auth-server-postgres_data:/var/lib/postgresql/data

volumes:
    auth-server-postgres_data:
