version: '3'

services:
    db:
        image: postgres
        restart: unless-stopped
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        volumes:
        - auth-server-pg-data:/var/lib/postgresql/data

volumes:
    auth-server-pg-data: